[package]
name = "phink"
description = "ink! smart-contract invariant-based coverage-guided fuzzer"
repository = "https://github.com/kevin-valerio/phink"
keywords = ["ink", "fuzz", "substrate"]
readme = "README.md"
authors = ["Kevin Valerio <kevin@srlabs.de>"]
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
default = ["std"]
tui = []
std = [
    "pallet-balances/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-contracts/std",
    "pallet-insecure-randomness-collective-flip/std",
    "parity-scale-codec/std",
    "scale-info/std",
]

[dependencies]

seq-macro = { version = "0.3.5" }
parity-scale-codec = { version = "3.6.9", default-features = false }
scale-info = { version = "2.6.0", default-features = false }
prettytable-rs = { version = "0.10.0" }
contract-metadata = { version = "4.1.1" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }

frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }

pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }
pallet-contracts = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }
pallet-insecure-randomness-collective-flip = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.0", default-features = false }


env_logger = { version = "0.11.3" }
ziggy = { version = "1.0.2", default-features = false }
wat = { version = "1.202.0" }
hex = { version = "0.4.3" }
hex-literal = { version = "0.4.1" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.115" }
ink_env = { version = "5.0.0" }
ink = { version = "5.0.0" }
contract-build = { version = "4.1.0" }
paste = { version = "1.0.14" }
anyhow = { version = "1.0.81" }
contract-transcode = { version = "4.1.0" }
itertools = { version = "0.13.0" }
strsim = { version = "0.11.1" }
tracing = { version = "0.1.40" }
ink_metadata = { version = "5.0.0" }
clap = { version = "4.5.4" , features = ["derive"]}
syn = { version = "2.0.60" , features = ["parsing", "full", "visit-mut"]}
quote = { version = "1.0.36" }
proc-macro2 = { version = "1.0.81", features = ["span-locations"]}
rand = { version = "0.8" }
walkdir = { version = "2.5.0" }
config = "0.14.0"

