# Phink Configuration

cores = 1
max_messages_per_exec = 4
report_path = "output/phink/contract_coverage"
use_honggfuzz = false
fuzz_origin = false
deployer_address = "5C62Ck4UrFPiBtoCmeSrgF7x9yv9mn38446dhCpsi2mLHiFT" #Alice (Origin(1))
#storage_deposit_limit = 10_000_000

[default_gas_limit]
ref_time = 100000000000
proof_size = 3145728  # 3 * 1024 * 1024